### ISSUE TITLE
Dice rolling and RPS

### ISSUE THREAD

**Issue by CFLombardi** [CFLombardi/sethBot#28]
It has been requested that we implement a dice rolling feature to the bot.  So you could type something like !2d20 and you produce the result.  Something akin to "Your d20 results are 7 and 18".  To clarify, the format of this command would be prefix+number of dice+type of dice

In addition, a rock, paper, scissors command.  !rps would be the command and would produce one of the following "rock/paper/scissors".

**Comment by CFLombardi** [comment]
Suggestion on module to use https://www.npmjs.com/package/roll

**Comment by CFLombardi** [comment]
It was asked to add an "Advantage/disadvantage" feature.  Example: !dice 2d20D would roll two d20s and only produce the lower result.  A would take the higher of the two.

**Comment by CFLombardi** [comment]
While the code has been merged, my thought is to keep the RPS feature tied to the dice command.  So perhaps we could add a check to see if !dice rps was typed and then spit back a random number for those.

**Comment by Kydane** [comment]
I dont know what "rps" is :(

**Comment by CFLombardi** [comment]
Closed by #45
