### ISSUE TITLE
Set up "karma" system.

### ISSUE THREAD

**Issue by Kydane** [CFLombardi/sethBot#4]
The system would work similar to the Reddit karma system in which a a user's message can have karma added to it.

The feature will work by listening for message reactions and based of two emojis, will act as an upvote and downvote. 
The following rules will be put into place:
* A person can not vote for themselves
* A person can not vote twice on the same Message.
* A message will be allowed for a determinate allowed of time based on a configuration property.

Each time someones karma changes, it should be written out to a file for persistence.

**Comment by Kydane** [comment]
Initial commit took care of:
~~A person can not vote for themselves~~
~~A person can not vote twice on the same Message.~~
A message will be allowed for a determinate allowed of time based on a configuration property.
~~Persistence~~

**Comment by Kydane** [comment]
a "!dosh [@mention]" command to handle users seeing how much dosh they have.
Still needs support for ++ and --

**Comment by CFLombardi** [comment]
Not sure if I should make a new issue for this or add to this one.  Something I'm noticing is that you can't check on someone's dosh if they are not in the channel because it relies on the @mention.  Do we want to adjust that so that you can message Seth directly and check on those stats?

**Comment by Kydane** [comment]
Yeah. We should also work in private messages to Seth too. I noticed that this morning as well. 
The real question is can you mention someone in private messages either?

**Comment by CFLombardi** [comment]
Support for ++ and -- is being tracked by https://github.com/CFLombardi/sethBot/issues/6

**Comment by CFLombardi** [comment]
I feel like this issue can be closed.  The karma (dosh) system is in place.
